controller:
  replicas: {{ args.replicas }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

  hostNetwork: true

  hostPort:
    enabled: true

  #nodeSelector:
  #  node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
